CREATE TABLE IF NOT EXISTS work_price(
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    price NUMERIC NOT NULL ,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    work_id UUID REFERENCES work(id)
)
