#server:
#  port: 8888

management:
  metrics:
    tags:
      application: carfix
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus
  prometheus:
    metrics:
      export:
        enabled: true



spring:
  application:
    name: Carfix-Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/Carfix
    username: postgres
    password: iamroot
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: carfix.app.mail@gmail.com
    password: flet xdrx tple rahi
    properties:
      mail:
        debug: debug
        smtp:
#          timeout: 5000
#          connectiontimeout: 5000
#          writetimeout: 5000
          auth: true
          starttls:
            enable: true

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855