#server:
#  port: 8888

management:
  metrics:
    tags:
      application: carfix
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus
  prometheus:
    metrics:
      export:
        enabled: true



spring:
  application:
    name: Carfix-Backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: carfix.app.mail@gmail.com
    password: ${MAIL_PASS}
    properties:
      mail:
        debug: debug
        smtp:
          auth: true
          starttls:
            enable: true
jasypt:
  encryptor:
    password: ${ENCRYPT_KEY}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    key-obtention-iterations: 2000
    pool-size: 4
    string-output-type: base64


token:
  signing:
    key: ${KEY}